### ISSUE TITLE
Any documentation on how to set up everything?

### ISSUE THREAD

**Issue by esQmo** [CovidWorld/server#3]
Please can you provide documentation on how to set the server up? 
Why not simply use Firebase for OTP?

**Comment by Daziko** [comment]
> Please can you provide documentation on how to set the server up?

You have many options how to deploy each function to cloud.
Azure pipelines: https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-functions?view=azure-devops&tabs=dotnet-core%2Cyaml
Manually: https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies

> Why not simply use Firebase for OTP?

If you want use firebase you can. Service is behind the interface you can provide own implementation.

**Comment by esQmo** [comment]
Thanks for the reply.
