### ISSUE TITLE
Errors executing tests on VS Code

### ISSUE THREAD

**Issue by esQmo** [CovidWorld/server#4]
Not experienced with Dotnet or C Sharp. I'm trying to run tests with `dotnet test C:\DEVELOPMENT\DOTNET\server\Sygic.Corona.Infrastructure.Tests\Sygic.Corona.Infrastructure.Tests.csproj` 4 pass but 3 fail with `The configuration file 'local.settings.json' was not found and is not optional. The physical path is 'C:\DEVELOPMENT\DOTNET\server\Sygic.Corona.Infrastructure.Tests\bin\Debug\netcoreapp3.1\local.settings.json'`
 Can you please assist ? I looked at the path in the error and the file doesn't exist

**Comment by Daziko** [comment]
Of course file doesn't exist because it is contains sensitive data like connection strings, secrets etc ... 
Those test are integration tests so you have to provide your own config file. It is enough to provide only values needed in specific test. In this case there is test for our private SMS gateway so of course there is no reason for you to run it.

**Comment by esQmo** [comment]
Thanks for the reply @Daziko . I know that the file contains sensitive data, I was thinking about a dummy file with dummy data describing each field. I was just trying to make it work as there is no much details on what does what. However it's a good initiative but you need to make it more understandable to the people willing to contribute to end this pandemic. 
So please help by providing more details on how to make it work,  like how the file should be named, its location....

**Comment by Daziko** [comment]
Desired values are in configuration description in read me file (README.md)
Example of azure function local config is bellow. Just provide your values. For esxample there is Twilio section so grab Twilio config keys from readme.md and provide values from your twilio account etc..
``` json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "YourSecretValue": "***-****",
    "YourSecretSetting": true
  }
}
```

**Comment by esQmo** [comment]
Thanks, will try that and let you know.

**Comment by esQmo** [comment]
@Daziko Tried to deploy to azure and have everything set up correctly (I guess) but when I try to access the API url, there is an error: Function host is not running. What could it be? The exact issues #5  ran into.
