### ISSUE TITLE
Error 401 from Android client

### ISSUE THREAD

**Issue by esQmo** [CovidWorld/server#6]
I **_finally_** managed to deploy the server to Azure, all set up and running. However, when the app launches, there is a HTTP 401 error popping.
The method that is being called at start up is the one for registering the device to the server. In the debugger I can see the data being sent but the server returns an error instead so the app can't pass to the next step.
I've found that the error might be that the function needs an authorization, but is set to anonymous

Below is a test made with Postman:

![image](https://user-images.githubusercontent.com/10319812/80265020-01173e80-868e-11ea-8b7e-30d1da016153.png)

Can you tell which function the client first calls at start up by executing `Api(context).createProfile() `call?

Thanks for you time.

**Comment by lyra-halcyon** [comment]
They seems not wanting people use their project or what??? No answer,nothing?
